development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: labo_reach_new_development
  pool: 5
  username: laboreachnew
  password: laboreachnew
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: labo_reach_new_test
  pool: 5
  username: laboreachnew
  password: laboreachnew
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: labo_reach_new_production
  pool: 5
  username: laboreachnew
  password: laboreachnew
  host: localhost
